kafka:
  app:
    - appId: 110
      key: eaab744bfd32b423b50761358e727424
      desc: 缓存平台
      topic:
        - id: AD_PROMOTE_CACHE_TOPIC
          desc: 投放更新
          url: http://pub.intra.uat.ffan.com/v1/msgs/AD_PROMOTE_CACHE_TOPIC/v1
        - id: AD_DSP_ENTITY_CACHE
          desc: DSP实体更新
          url: http://pub.intra.uat.ffan.com/v1/msgs/AD_DSP_ENTITY_CACHE/v1
        - id: AD_DSP_CREATION_CACHE
          desc: DSP创意实体更新
          url: http://pub.intra.uat.ffan.com/v1/msgs/DSP创意实体更新/v1
